version: 0.2
phases:
  install:
    runtime-versions:
  nodejs: 20
    commands:
      - npm install -g @angular/cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --configuration=production
  post_build:
    commands:
      - echo "Build completed successfully."
artifacts:
  files:
    - "**/*"
  base-directory: "dist/MarioFEProto"
  discard-paths: no
